# Generated by Django 2.2.4 on 2019-09-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0013_auto_20190905_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseno',
            name='base64',
        ),
        migrations.RemoveField(
            model_name='diseno',
            name='base64_modificado',
        ),
    ]
