# Generated by Django 2.2.4 on 2019-09-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0014_auto_20190924_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno',
            name='url_archivo',
            field=models.ImageField(upload_to='noProcesadas'),
        ),
    ]
