# Generated by Django 2.2.4 on 2019-09-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0015_auto_20190925_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='url_archivo',
            new_name='archivo',
        ),
    ]
