# Generated by Django 2.2.4 on 2019-10-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0017_auto_20190925_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='empresa',
            field=models.CharField(max_length=500),
        ),
    ]
