# Generated by Django 2.2 on 2019-09-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diseño',
            new_name='Diseno',
        ),
    ]
