# Generated by Django 2.2.4 on 2019-09-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='url',
        ),
    ]
