# Generated by Django 2.2.4 on 2019-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_remove_usercustom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='url',
            field=models.CharField(default='url', max_length=500),
        ),
    ]
