# Generated by Django 2.2.4 on 2019-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0005_auto_20190905_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='urlArchivo',
            new_name='url_archivo',
        ),
    ]
