# Generated by Django 2.2.4 on 2019-09-05 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0006_auto_20190905_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='base64',
            field=models.CharField(max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='diseno',
            name='url_archivo_modificado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
