# Generated by Django 2.2.4 on 2019-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0016_auto_20190925_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno',
            name='url_archivo_modificado',
            field=models.ImageField(null=True, upload_to='disponibles'),
        ),
    ]
